FROM php:8.0-apache

# Install mysqli
RUN docker-php-ext-install mysqli

# Copy secure files
COPY . /var/www/html/

# Fix permissions
RUN chmod -R 755 /var/www/html/

# Enable Apache mod_rewrite
RUN a2enmod rewrite

EXPOSE 80